# Generated by Django 3.1 on 2020-08-31 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='progress',
            new_name='is_complete',
        ),
    ]
