# Generated by Django 3.1 on 2020-09-01 11:34

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0002_auto_20200831_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='create_at',
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(2020, 9, 1, 11, 34, 6, 84710, tzinfo=utc),
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='page',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='task',
            name='create_at',
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
