# Generated by Django 3.1 on 2020-09-17 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0004_auto_20200901_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='title',
            field=models.CharField(default=1, max_length=32),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='page',
            name='title',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.CharField(max_length=256),
        ),
    ]
