# Generated by Django 3.1 on 2020-11-22 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0008_auto_20201008_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='page',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='tasks',
                to='todo_list.page',
            ),
        ),
    ]
